help:
  auth: Read auth info from <file>
  starting: Only get historical scans after <when> (ISO-8601 format)
  ending: Only get historical scans till <when> (ISO-8601 format)
  module: Specify by (CSM FIM SVM SAM)
  localca: Use local CA file (needed on Windows)
  threads: Set number of threads to use downloading scan results